package com.manuanand.helpdesk;

import java.util.Date;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/helpdesk") // This means URL's start with /helpdesk (after Application path)
public class TicketController {
	@Autowired // This means to get the bean called ticketRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private TicketRepository ticketRepository;
	
	///
	// Ticket Repository
	///
	@PostMapping(path="/addTicket") // Map ONLY POST Requests
	public @ResponseBody String addTicket (@RequestParam String title, 
			@RequestParam String category, @RequestParam String description,
			@RequestParam String userEmail) {

		Ticket newTicket = new Ticket();
		newTicket = populateTicket(newTicket, title, category, description, userEmail);
		ticketRepository.save(newTicket);
		
		return "Saved";
	}

	@GetMapping(path="/getAllTickets")
	public @ResponseBody Iterable<Ticket> getTickets() {
		
		// This returns a JSON or XML with the users
		return ticketRepository.findAll();
	}
	
	@GetMapping(path="/getTicketById")
	public @ResponseBody Ticket getTicketById(@RequestParam int id) {
		
		Optional<Ticket> ticket = ticketRepository.findById(id);
		if (!ticket.isEmpty()) {
			return ticket.get();
		} 
		
		return null;
	}
	
	///
	/// Helper Methods
	///
	private Ticket populateTicket( Ticket newTicket, String title, String category, String description, String userEmail)
	{
		newTicket.setTitle(title);
		newTicket.setCategory(category);
		newTicket.setDescription(description);
		newTicket.setUserEmail(userEmail);
		
		// Set auto-generated fields
		newTicket.setCreatedDate(new Date());
		newTicket.setStatus(TicketStatus.CREATED);
		
		return newTicket;
	}
}